"species","rec_gbif"
"Coragyps atratus",2153
"Cacicus cela",1965
"Tyrannus melancholicus",1897
"Thraupis episcopus",1893
"Psarocolius angustifrons",1886
"Ramphocelus carbo",1872
"Brotogeris versicolurus",1553
"Pitangus sulphuratus",1405
"Crotophaga ani",1365
"Rupornis magnirostris",1337
"Milvago chimachima",1329
"Thraupis palmarum",1256
"Monasa nigrifrons",1122
"Cathartes aura",1079
"Chionomesa fimbriata",978
"Turdus ignobilis",968
"Ardea alba",952
"Crotophaga major",926
"Sporophila castaneiventris",905
"Troglodytes aedon",903
"Jacana jacana",901
"Myiozetetes similis",896
"Megaceryle torquata",877
"Graydidascalus brachyurus",876
"Phaetusa simplex",867
"Capito aurovirens",852
"Tachornis squamata",836
"Patagioenas cayennensis",835
"Ammodramus aurifrons",769
"Crypturellus undulatus",766
"Melanerpes cruentatus",765
"Aratinga weddellii",755
"Butorides striata",747
"Tyrannulus elatus",721
"Paroaria gularis",672
"Megarynchus pitangua",649
"Columbina talpacoti",638
"Todirostrum maculatum",624
"Trogon viridis",621
"Pteroglossus castanotis",620
"Campylorhynchus turdinus",607
"Capito auratus",603
"Busarellus nigricollis",603
"Thamnophilus doliatus",594
"Aratinga leucophthalma",579
"Anhima cornuta",573
"Tangara mexicana",572
"Xiphorhynchus picus",567
"Ramphastos tucanus",563
"Tityra cayana",541
"Leptotila rufaxilla",539
"Ortalis guttata",538
"Donacobius atricapilla",529
"Pionus menstruus",510
"Chaetura brachyura",509
"Ara severus",499
"Phalacrocorax brasilianus",495
"Ictinia plumbea",493
"Tachycineta albiventer",489
"Brotogeris sanctithomae",483
"Piaya cayana",477
"Chloroceryle amazona",469
"Stelgidopteryx ruficollis",469
"Amazona festiva",461
"Patagioenas plumbea",454
"Sternula superciliaris",448
"Cathartes melambrotus",439
"Saltator coerulescens",436
"Campephilus melanoleucos",434
"Chrysomus icterocephalus",407
"Pheugopedius coraya",403
"Ara macao",401
"Cantorchilus leucotis",399
"Celeus flavus",394
"Daptrius ater",389
"Pitangus lictor",386
"Xiphorhynchus guttatus",386
"Volatinia jacarina",376
"Colaptes punctigula",375
"Gymnoderus foetidus",374
"Megascops choliba",369
"Lepidothrix coronata",368
"Ramphocelus nigrogularis",363
"Columba livia",359
"Pachyramphus polychopterus",354
"Orthopsittaca manilata",350
"Thlypopsis sordida",345
"Dryocopus lineatus",341
"Herpetotheres cachinnans",341
"Glyphorynchus spirurus",338
"Myiodynastes maculatus",335
"Ardea cocoi",333
"Amazona farinosa",330
"Patagioenas subvinacea",328
"Nasica longirostris",326
"Glaucidium brasilianum",325
"Ibycter americanus",322
"Euphonia laniirostris",320
"Pipra erythrocephala",316
"Oryzoborus angolensis",314
"Celeus elegans",309
"Attila spadiceus",306
"Pandion haliaetus",303
"Vireo olivaceus",300
"Phaeomyias murina",296
"Nemosia pileata",296
"Buteogallus urubitinga",293
"Crypturellus cinereus",290
"Galbalcyrhynchus leucotis",289
"Progne elegans",284
"Ara ararauna",284
"Euphonia minuta",282
"Anthracothorax nigricollis",281
"Myrmotherula brachyura",281
"Trogon melanurus",279
"Icterus icterus",278
"Pteroglossus pluricinctus",277
"Tyrannus savana",277
"Myiarchus ferox",276
"Egretta thula",272
"Mesembrinibis cayennensis",272
"Bubulcus ibis",270
"Querula purpurata",269
"Sporophila murallae",267
"Chloroceryle americana",261
"Ramphastos vitellinus",259
"Leucopternis schistaceus",252
"Thamnophilus murinus",250
"Phaethornis hispidus",247
"Porphyrio martinica",244
"Molothrus oryzivorus",244
"Mionectes oleagineus",238
"Nyctidromus albicollis",235
"Tyrannus albogularis",234
"Pyrrhura melanura",231
"Gymnomystax mexicanus",231
"Lipaugus vociferans",231
"Talaphorus chlorocercus",229
"Legatus leucophaius",229
"Cathartes burrovianus",225
"Myrmeciza melanoceps",221
"Microcerculus marginatus",218
"Thalurania furcata",216
"Tigrisoma lineatum",216
"Dendrocincla fuliginosa",216
"Pionites melanocephalus",215
"Euphonia chlorotica",209
"Arundinicola leucocephala",209
"Cacicus solitarius",209
"Poecilotriccus latirostris",208
"Progne tapera",208
"Cephalopterus ornatus",207
"Zimmerius gracilipes",207
"Cyanerpes caeruleus",200
"Dacnis flaviventer",199
"Progne chalybea",199
"Furnarius minor",199
"Celeus grammicus",196
"Glaucis hirsutus",195
"Chloroceryle inda",194
"Cotinga maynana",193
"Saltator maximus",193
"Dendrexetastes rufigula",192
"Myiozetetes granadensis",188
"Euphonia xanthogaster",187
"Hypocnemis peruviana",187
"Euphonia chrysopasta",186
"Taraba major",185
"Hirundo rustica",182
"Cercomacra cinerascens",181
"Forpus xanthopterygius",180
"Veniliornis passerinus",179
"Anhinga anhinga",178
"Attila bolivianus",177
"Tangara chilensis",175
"Opisthocomus hoazin",175
"Cairina moschata",175
"Psarocolius decumanus",175
"Camptostoma obsoletum",174
"Phaethornis bourcieri",171
"Myiarchus tuberculifer",170
"Schiffornis major",170
"Sporophila lineola",167
"Falco rufigularis",166
"Bucco tamatia",165
"Nyctibius grandis",159
"Nycticorax nycticorax",158
"Rostrhamus sociabilis",156
"Euphonia rufiventris",155
"Hypocnemis hypoxantha",155
"Pteroglossus inscriptus",152
"Chloroceryle aenea",148
"Heliornis fulica",148
"Phaethornis ruber",146
NULL,142
"Tapera naevia",142
"Tyranneutes stolzmanni",141
"Todirostrum chrysocrotaphum",141
"Florisuga mellivora",141
"Charadrius collaris",140
"Ochthornis littoralis",137
"Rynchops niger",137
"Pilherodius pileatus",136
"Phaethornis malaris",136
"Piaya minuta",136
"Brotogeris cyanoptera",135
"Tityra semifasciata",134
"Cissopis leverianus",134
"Tyrannopsis sulphurea",134
"Leptotila verreauxi",133
"Trogon collaris",131
"Pyrocephalus rubinus",128
"Vanellus chilensis",126
"Sicalis flaveola",125
"Molothrus bonariensis",125
"Actitis macularius",125
"Leptodon cayanensis",122
"Myrmoborus myotherinus",120
"Tolmomyias poliocephalus",118
"Coccyzus melacoryphus",117
"Penelope jacquacu",117
"Tityra inquisitor",116
"Cyanocorax violaceus",115
"Elanoides forficatus",114
"Amazona amazonica",114
"Synallaxis albigularis",112
"Schistocichla leucostigma",112
"Certhiaxis mustelinus",111
"Tinamus major",111
"Xiphorhynchus obsoletus",110
"Picumnus castelnau",108
"Thamnophilus cryptoleucus",108
"Attila cinnamomeus",107
"Galbula albirostris",105
"Myrmotherula axillaris",104
"Chiroxiphia pareola",104
"Crypturellus soui",102
"Willisornis poecilinotus",101
"Tangara schrankii",100
"Tinamus guttatus",100
"Sturnella militaris",99
"Pionopsitta barrabandi",98
"Turdus hauxwelli",98
"Myrmeciza fortis",97
"Cnipodectes subbrunneus",97
"Myiozetetes luteiventris",97
"Helicolestes hamatus",95
"Percnostola rufifrons",95
"Megascops watsonii",94
"Attila citriniventris",94
"Turdus sanchezorum",93
"Galbula dea",92
"Tringa solitaria",92
"Hoploxypterus cayanus",92
"Gymnopithys leucaspis",91
"Cymbilaimus lineatus",91
"Pachyramphus castaneus",90
"Crypturellus variegatus",89
"Liosceles thoracicus",89
"Furnarius leucopus",88
"Sporophila bouvronides",88
"Sakesphorus canadensis",87
"Icterus cayanensis",86
"Elaenia parvirostris",86
"Eurypyga helias",86
"Trogon ramonianus",86
"Lophotriccus vitiosus",86
"Galbula tombacea",85
"Riparia riparia",85
"Sclateria naevia",84
"Progne subis",84
"Atticora fasciata",83
"Xiphorhynchus elegans",83
"Myrmotherula assimilis",83
"Chaetura cinereiventris",83
"Dendrocolaptes picumnus",82
"Geranospiza caerulescens",82
"Dendrocolaptes certhia",81
"Trogon curucui",80
"Synallaxis gujanensis",80
"Myrmochanes hemileucus",79
"Selenidera reinwardtii",79
"Egretta caerulea",79
"Schistocichla schistacea",78
"Isleria hauxwelli",77
"Thamnophilus schistaceus",77
"Thamnomanes caesius",75
"Ocyalus latirostris",75
"Threnetes leucurus",75
"Phlegopsis nigromaculata",75
"Amazona ochrocephala",74
"Tolmomyias flaviventris",74
"Chlorestes notata",74
"Nyctibius griseus",74
"Chelidoptera tenebrosa",74
"Xiphorhynchus ocellatus",73
"Chlorostilbon mellisugus",73
"Pulsatrix perspicillata",73
"Myiozetetes cayanensis",73
"Manacus manacus",72
"Cotinga cayana",72
"Buteo albonotatus",72
"Thamnomanes ardesiacus",71
"Myrmoborus lugubris",71
"Campephilus rubricollis",71
"Aramus guarauna",70
"Empidonomus aurantioatrocristatus",70
"Lampropsar tanagrinus",70
"Eucometis penicillata",69
"Aburria cumanensis",69
"Saltator grossus",66
"Campylopterus largipennis",66
"Monasa morphoeus",66
"Psarocolius bifasciatus",66
"Tangara velia",65
"Dendrocygna autumnalis",63
"Pipra filicauda",63
"Chordeiles rupestris",62
"Tachyphonus surinamus",62
"Pachyramphus marginatus",62
"Dacnis cayana",61
"Veniliornis affinis",60
"Phaethornis atrimentalis",60
"Turdus albicollis",60
"Myrmothera campanisona",60
"Cnemotriccus fuscatus",60
"Empidonomus varius",60
"Geotrygon montana",59
"Pteroglossus azara",59
"Trogon rufus",58
"Piculus flavigula",58
"Momotus momota",58
"Aramides cajanea",57
"Myiopagis gaimardii",56
"Hydropsalis climacocerca",56
"Sarcoramphus papa",56
"Panyptila cayennensis",55
"Ornithion inerme",54
"Buteo nitidus",54
"Myrmotherula menetriesii",52
"Furnarius torridus",52
"Chondrohierax uncinatus",51
"Phoenicircus nigricollis",51
"Turdus lawrencii",51
"Laterallus exilis",51
"Harpagus bidentatus",50
"Myrmotherula multostriata",49
"Thamnophilus amazonicus",48
"Cyphorhinus arada",47
"Sittasomus griseicapillus",47
"Pachyramphus minor",47
"Chrysuronia oenone",47
"Laniocera hypopyrra",46
"Rhytipterna simplex",46
"Forpus modestus",45
"Corythopis torquatus",45
"Porphyrio flavirostris",44
"Chlorophanes spiza",44
"Nothocrax urumutum",43
"Calidris melanotos",43
"Terenotriccus erythrurus",42
"Tachyphonus cristatus",42
"Psophia crepitans",42
"Serpophaga hypoleuca",42
"Myrmeciza hyperythra",41
"Knipolegus poecilocercus",41
"Pithys albifrons",41
"Caracara plancus",40
"Berlepschia rikeri",39
"Metopothrix aurantiaca",38
"Schiffornis turdina",38
"Myiornis ecaudatus",38
"Pharomachrus pavoninus",38
"Eubucco richardsoni",37
"Hylophylax naevius",37
"Pygiptila stellaris",37
"Cochlearius cochlearius",37
"Conopophaga aurita",37
"Megastictus margaritatus",37
"Mycteria americana",37
"Bucco macrodactylus",37
"Xiphocolaptes promeropirhynchus",36
"Lepidocolaptes duidae",36
"Psarocolius viridis",36
"Certhiaxis cinnamomeus",36
"Bucco capensis",35
"Athene cunicularia",35
"Ara chloropterus",35
"Buteo brachyurus",35
"Dendroplex kienerii",34
"Formicarius colma",34
"Machaeropterus striolatus",33
"Dendrocincla merula",33
"Cyanerpes cyaneus",33
"Formicarius analis",33
"Rhynchocyclus olivaceus",33
"Petrochelidon pyrrhonota",33
"Conopias albovittatus",33
"Odontophorus gujanensis",33
"Myrmoborus melanurus",32
"Dromococcyx phasianellus",32
"Iodopleura isabellae",32
"Streptoprocne zonaris",31
"Piaya melanogaster",31
"Hylophilus hypoxanthus",31
"Elaenia spectabilis",30
"Crax globulosa",30
"Cyanerpes nitidus",30
"Chrysuronia versicolor",30
"Hemithraupis flavicollis",30
"Lanio fulvus",29
"Heliothryx auritus",28
"Ramphotrigon ruficauda",28
"Hemithraupis guira",27
"Myiopagis flavivertex",27
"Pipra pipra",27
"Hylophilus semicinereus",27
"Setophaga petechia",26
"Jacamerops aureus",26
"Porphyrolaema porphyrolaema",26
"Spizaetus tyrannus",26
"Agamia agami",26
"Herpsilochmus dorsimaculatus",26
"Monasa flavirostris",26
"Dichrozona cincta",26
"Myrmotherula ignota",26
"Philydor pyrrhodes",25
"Xenops minutus",25
"Celeus torquatus",25
"Loriotus luctuosus",25
"Elaenia flavogaster",25
"Notiochelidon cyanoleuca",25
"Sclerurus caudacutus",25
"Knipolegus orenocensis",24
"Nyctibius aethereus",24
"Contopus virens",24
"Myrmotherula longipennis",24
"Automolus infuscatus",24
"Henicorhina leucosticta",23
"Cercomacra serva",23
"Grallaria dignissima",23
"Touit purpuratus",23
"Chordeiles nacunda",23
"Neopelma chrysocephalum",23
"Coereba flaveola",23
"Heliodoxa aurescens",22
"Tolmomyias assimilis",22
"Hylophilus thoracicus",22
"Leucopternis melanops",22
"Malacoptila fusca",22
"Myiarchus swainsoni",22
"Onychorhynchus coronatus",22
"Piprites chloris",21
"Notharchus tectus",21
"Baryphthengus martii",21
"Tangara callophrys",21
"Hypocnemoides maculicauda",21
"Notharchus hyperrhynchus",21
"Tringa flavipes",21
"Zonotrichia capensis",20
"Tyrannus tyrannus",20
"Xenops milleri",20
"Hemitriccus zosterops",20
"Platyrinchus coronatus",20
"Cercomacra nigrescens",20
"Chordeiles minor",19
"Strix huhula",19
"Falco peregrinus",19
"Tersina viridis",19
"Heliomaster longirostris",19
"Hypocnemoides melanopogon",19
"Philydor erythropterum",19
"Tolmomyias sulphurescens",18
"Nyctipolus nigrescens",18
"Cyanoloxia rothschildii",18
"Heliodoxa schreibersii",18
"Thamnophilus aethiops",18
"Habia rubica",18
"Coccyzus cinereus",18
"Synallaxis propinqua",18
"Automolus ochrolaemus",18
"Cranioleuca gutturata",17
"Piculus chrysochloros",17
"Phlegopsis erythroptera",17
"Micrastur semitorquatus",17
"Dacnis lineata",17
"Sporophila caerulescens",17
"Conirostrum margaritae",17
"Cacicus haemorrhous",17
"Lurocalis semitorquatus",16
"Myiopagis caniceps",16
"Catharus ustulatus",16
"Vireo leucophrys",16
"Setophaga striata",16
"Sporophila nigricollis",16
"Philydor ruficaudatum",16
"Myiodynastes luteiventris",15
"Chlorestes cyanus",15
"Columbina minuta",15
"Topaza pyra",15
"Herpsilochmus dugandi",15
"Cranioleuca vulpina",14
"Chamaeza nobilis",14
"Lophostrix cristata",14
"Lophotriccus galeatus",14
"Hylophylax punctulatus",14
"Chlorostilbon olivaresi",14
"Deconychura longicauda",14
"Gampsonyx swainsonii",14
"Conirostrum bicolor",14
"Polytmus theresiae",14
"Synallaxis albescens",14
"Hyloctistes subulatus",14
"Zenaida auriculata",14
"Patagioenas speciosa",13
"Pachyramphus rufus",13
"Nonnula rubecula",13
"Anurolimnas fasciatus",13
"Claravis pretiosa",13
"Platalea ajaja",13
"Accipiter superciliosus",13
"Spizaetus melanoleucus",13
"Muscisaxicola fluviatilis",13
"Psarocolius oseryi",13
"Dacnis albiventris",12
"Cyclarhis gujanensis",12
"Cranioleuca vulpecula",12
"Galbula leucogastra",12
"Hylophilus ochraceiceps",12
"Columbina passerina",12
"Lathrotriccus euleri",12
"Micrastur gilvicollis",12
"Mitu tuberosum",12
"Myrmeciza atrothorax",12
"Picumnus lafresnayi",12
"Tangara gyrola",12
"Piranga rubra",11
"Piranga olivacea",11
"Ancistrops strigilatus",11
"Neochelidon tibialis",11
"Coccyzus americanus",11
"Sirystes albocinereus",10
"Hypocnemis flavescens",10
"Tachyphonus phoenicius",10
"Stigmatura napensis",10
"Tolmomyias traylori",10
"Stilpnia cayana",10
"Epinecrophylla erythrura",10
"Campylorhamphus procurvoides",10
"Empidonax alnorum",10
"Deconychura stictolaema",10
"Ramphocaenus melanurus",9
"Laterallus melanophaius",9
"Atticora melanoleuca",9
"Contopus cooperi",9
"Spizaetus ornatus",9
"Myrmoborus leucophrys",9
"Geotrygon saphirina",9
"Microbates collaris",9
"Frederickena fulva",9
"Strix virgata",9
"Vireo flavoviridis",9
"Elaenia cristata",9
"Tryngites subruficollis",9
"Myiotheretes striaticollis",8
"Hemitriccus granadensis",8
"Ictinia mississippiensis",8
"Scytalopus unicolor",8
"Calidris minutilla",8
"Capsiempis flaveola",8
"Diglossa cyanea",8
"Grallaria rufula",8
"Geranoaetus melanoleucus",8
"Progne modesta",8
"Pseudotriccus ruficeps",8
"Atlapetes rufinucha",8
"Mecocerculus leucophrys",8
"Polioptila plumbea",8
"Ochthoeca rufipectoralis",8
"Tringa melanoleuca",8
"Urothraupis stolzmanni",8
"Pluvialis dominica",7
"Mitu tomentosum",7
"Catharus minimus",7
"Phaethornis superciliosus",7
"Rupicola rupicola",7
"Geothlypis aequinoctialis",7
"Conirostrum speciosum",7
"Accipiter poliogaster",7
"Rhegmatorhina melanosticta",7
"Schistochlamys melanopis",7
"Myiobius barbatus",7
"Neoctantes niger",7
"Galbula chalcothorax",7
"Sublegatus obscurior",7
"Machetornis rixosa",7
"Crypturellus bartletti",7
"Anisognathus igniventris",6
"Thraupis cyanocephala",6
"Conirostrum sitticolor",6
"Todirostrum cinereum",6
"Diglossa lafresnayii",6
"Pseudoscops clamator",6
"Dubusia taeniata",6
"Buthraupis eximia",6
"Capito niger",6
"Nomonyx dominicus",6
"Neopipo cinnamomea",6
"Neomorphus pucheranii",6
"Ampelion rubrocristatus",6
"Epinecrophylla haematonota",6
"Myiothlypis fulvicauda",6
"Myiothlypis coronata",6
"Myioborus ornatus",6
"Turdus serranus",6
"Chordeiles pusillus",6
"Sporophila minuta",6
"Micrastur ruficollis",6
"Turdus fuscater",6
"Platyrinchus platyrhynchos",6
"Anisognathus lacrymosus",6
"Calliphlox amethystina",6
"Tangara nigrocincta",6
"Tangara vassorii",6
"Formicivora grisea",6
"Iridosornis rufivertex",6
"Colonia colonus",5
"Elaenia chiriquensis",5
"Mitu salvini",5
"Cercomacra tyrannina",5
"Tigrisoma fasciatum",5
"Tangara xanthogastra",5
"Xenops tenuirostris",5
"Accipiter bicolor",5
"Nyctiprogne leucopyga",5
"Catharus fuscescens",5
"Sclerurus mexicanus",5
"Bartramia longicauda",5
"Elaenia strepera",5
"Buteo platypterus",5
"Eudocimus ruber",5
"Zebrilus undulatus",5
"Buteo swainsoni",5
"Heterocercus aurantiivertex",5
"Elaenia ruficeps",5
"Calidris fuscicollis",4
"Notharchus ordii",4
"Phimosus infuscatus",4
"Harpia harpyja",4
"Micrastur mirandollei",4
"Elaenia frantzii",4
"Synallaxis rutilans",4
"Leptopogon amaurocephalus",4
"Dolichonyx oryzivorus",4
"Falco sparverius",4
"Hylocharis sapphirina",4
"Thamnophilus nigrocinereus",4
"Inezia subflava",4
"Calidris himantopus",4
"Terenura spodioptila",4
"Neocrex erythrops",4
"Calidris alba",3
"Cyanocompsa cyanoides",3
"Metallura tyrianthina",3
"Hylopezus macularius",3
"Deroptyus accipitrinus",3
"Setophaga ruticilla",3
"Heterocercus flavivertex",3
"Boissonneaua flavescens",3
"Picumnus pumilus",3
"Eriocnemis mosquera",3
"Brachygalba lugubris",3
"Micromonacha lanceolata",3
"Eriocnemis vestita",3
"Elanus leucurus",3
"Patagioenas fasciata",3
"Myrmotherula ambigua",3
"Caryothraustes canadensis",3
"Philydor erythrocercum",3
"Tachyphonus rufus",3
"Coeligena torquata",3
"Aulacorhynchus prasinus",3
"Myiarchus cephalotes",3
"Morphnus guianensis",3
"Hylophilus flavipes",2
"Oressochen jubatus",2
"Buteo albicaudatus",2
"Ramphotrigon fuscicauda",2
"Notharchus macrorhynchos",2
"Burhinus bistriatus",2
"Schizoeaca fuliginosa",2
"Sclerurus obscurior",2
"Microrhopias quixensis",2
"Machaeropterus regulus",2
"Leucopternis albicollis",2
"Aulacorhynchus haematopygus",2
"Colaptes rubiginosus",2
"Jabiru mycteria",2
"Pionopsitta pyrilia",2
"Hylophilus brunneiceps",2
"Himantopus mexicanus",2
"Aratinga pertinax",2
"Tinamus tao",2
"Hemitriccus margaritaceiventer",2
"Habia fuscicauda",2
"Gallus gallus",2
"Cotinga cotinga",2
"Crax alector",2
"Turdus leucomelas",2
"Elaenia pelzelni",2
"Doryfera johannae",2
"Hydropsalis maculicaudus",1
"Tringa semipalmata",1
"Columbina squammata",1
"Polytmus guainumbi",1
"Terenura callinota",1
"Ixobrychus exilis",1
"Tangara cayana",1
"Falco deiroleucus",1
"Poecilotriccus sylvia",1
"Trogon violaceus",1
"Tachyphonus luctuosus",1
"Leucophaeus atricilla",1
"Leucophaeus pipixcan",1
"Sturnella magna",1
"Micrastur buckleyi",1
"Chrysolampis mosquitus",1
"Sicalis luteola",1
"Calochaetes coccineus",1
"Momotus aequatorialis",1
"Sclerurus rufigularis",1
"Epinecrophylla ornata",1
"Chlorornis riefferii",1
"Sayornis nigricans",1
"Saucerottia hoffmanni",1
"Amazonetta brasiliensis",1
"Brotogeris jugularis",1
"Rhytipterna immunda",1
"Tyto alba",1
"Numenius phaeopus",1
"Ramphocelus dimidiatus",1
"Quiscalus mexicanus",1
"Chamaeza campanisona",1
"Vireo altiloquus",1
"Chaetura pelagica",1
"Dendrocygna viduata",1
"Chaetura meridionalis",1
"Buteogallus meridionalis",1
"Butorides virescens",1
"Chaetocercus mulsant",1
"Parkerthraustes humeralis",1
"Parkesia noveboracensis",1
"Picumnus squamulatus",1
"Xipholena punicea",1
"Phaethornis longuemareus",1
"Discosura langsdorffi",1
"Porzana carolina",1
"Porzana albicollis",1
"Glaucidium hardyi",1
"Ardea herodias",1
"Arremon taciturnus",1
"Touit huetii",1
"Theristicus caudatus",1
"Pharomachrus antisianus",1
